{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json #to convert list and dictionary to json\n",
    "import os\n",
    "import requests\n",
    "from flask import Flask #it is microframework to develop a web app\n",
    "from flask import request\n",
    "from flask import make_response\n",
    "#Falsk app for our web app\n",
    "app=Flask(__name__)\n",
    "# app route decorator. when webhook is called, the decorator would call the functions which are e defined\n",
    "@app.route('/webhook', methods=['POST'])\n",
    "def webhook():\n",
    "    # convert the data from json.\n",
    "    req=request.get_json(silent=True, force=True)\n",
    "    print(json.dumps(req, indent=4))\n",
    "    #extract the relevant information and use api and get the response and send it dialogflow.\n",
    "    #helper function\n",
    "    res=makeResponse(req)\n",
    "    res=json.dumps(res, indent=4)\n",
    "    r=make_response(res)\n",
    "    r.headers['Content-Type']='application/json'\n",
    "    return r\n",
    "\n",
    "# extract parameter values, query weahter api, construct the resposne\n",
    "def makeResponse(req):\n",
    "    result=req.get(\"queryResult\")\n",
    "    parameters=result.get(\"parameters\")\n",
    "    city=parameters.get(\"geo-city\")\n",
    "    date=parameters.get(\"date\")\n",
    "    \n",
    "r=requests.get('http://api.openweathermap.org/data/2.5/forecast?q=hyderabad,in&appid=db91df44baf43361cbf73026ce5156cb')\n",
    "json_object=r.json()\n",
    "weather=json_object['list']\n",
    "\n",
    "\n",
    "#for i in range(0,40):\n",
    "# if date in weather[i]['dt_txt']:\n",
    "# condition=weather[i]['weather'][0]['description']\n",
    "condition=weather[0]['weather'][0]['description']\n",
    "speech=\"The forecast for \"+city+ \" for \"+date+\" is \"+ condition\n",
    "return{\n",
    "    \"fulfillmentMessages\": [\n",
    "        {\n",
    "            \"text\": {\n",
    "                \"text\": speech\n",
    "            }\n",
    "        }]}\n",
    "\n",
    "#return {\n",
    "# \"speech\": speech,\n",
    "# \"displayText\":speech,\n",
    "# \"source\":\"apiai-weather-webhook\"}\n",
    "\n",
    "if __name__=='__main__':\n",
    "    port=int(os.getenv('PORT',5000))\n",
    "    print(\"starting on port %d\" % port)\n",
    "    app.run(debug=False, port=port, host='0.0.0.0')\n",
    "    \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
